# Generated by Django 3.2.18 on 2024-03-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='signData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('signature', models.FileField(max_length=500, null=True, upload_to='')),
                ('adderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendsignapp.log')),
            ],
        ),
    ]
