# Generated by Django 3.2.18 on 2024-03-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsignapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signdata',
            name='signature',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
